binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: utility-ht 0.0.10

  Hackage: probability 0.2.4

  Hackage: ieee 0.6.1'
ghc-args: []
excluded-modules:
- src/Challenges.hs
